#!/usr/bin/env zsh
local venvs_world=${XDG_DATA_HOME:-$HOME/.local/share}/venvs
venvs_path () {
    ([[ $(command -v md5sum) ]] && echo "$venvs_world/$(printf "${${1:-$(pwd)}:P}" | md5sum | cut -d ' ' -f 1)") ||
                                   echo "$venvs_world/$(md5 -qs "${${1:-$(pwd)}:P}")"
}
exec $(venvs_path ${1:P})/venv/bin/$2 ${@:3}
