version: 2.1
jobs:
  demo_container:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run: apt-get -y install software-properties-common
      - run: add-apt-repository -y ppa:alexlarsson/flatpak
      - run: add-apt-repository -y ppa:gophers/archive
      - run: apt-add-repository -y ppa:projectatomic/ppa
      - run: apt-get -y -qq update
      - run: apt-get -y install bats btrfs-tools git libapparmor-dev libdevmapper-dev libglib2.0-dev libgpgme11-dev libseccomp-dev libselinux1-dev skopeo-containers go-md2man
      - run: apt-get -y install golang-1.12
      - run: mkdir ~/buildah
      - run: cd ~/buildah
      - run: export GOPATH=`pwd`
      - run: git clone https://github.com/containers/buildah ./src/github.com/containers/buildah
      - run: cd ./src/github.com/containers/buildah
      - run: PATH=/usr/lib/go-1.10/bin:$PATH make runc all SECURITYTAGS="apparmor seccomp"
      - run: sudo make install install.runc
      - run: buildah --help
      - checkout
      - run: sh -e ./mk/demo_ctnr.sh
      - run: buildah login -u="andykluger+circle_ci" -p="$QUAY_TOKEN" quay.io
      - run: buildah push quay.io/andykluger/zim-alpine:latest
      - run: buildah push quay.io/andykluger/zpy-alpine:latest
      - run: buildah push quay.io/andykluger/zpy-alpine:develop
workflows:
  build_and_push:
    jobs:
      - demo_container
