version: 2.1
jobs:
  demo_container:
    docker:
      - image: quay.io/buildah/stable:v1.12.0
    steps:
      - checkout
      - run: ./mk/demo_ctnr.sh
      - run: buildah login -u="andykluger+circle_ci" -p="$QUAY_TOKEN" quay.io
      - run: buildah push quay.io/andykluger/zim-alpine:latest
      - run: buildah push quay.io/andykluger/zpy-alpine:latest
      - run: buildah push quay.io/andykluger/zpy-alpine:develop
workflows:
  build_and_push:
    jobs:
      - demo_container
